model_args:
  decoder_depth: 8
  decoder_embed_dim: 512
  decoder_num_heads: 16
  depth: 32
  embed_dim: 1280
  img_size: 224
  in_chans: 6
  num_frames: 1
  num_heads: 16
  patch_size: 14
  tubelet_size: 1
train_params:
  bands:
    - B01
    - B02
    - B03
    - B08
    - B011
    - B012
  data_mean:
    - 0.14245495
    - 0.13921481
    - 0.12434631
    - 0.31420089
    - 0.20743526
    - 0.12046503
  data_std:
    - 0.04036231
    - 0.04186983
    - 0.05267646
    - 0.0822221
    - 0.06834774
    - 0.05294205
  mask_ratio: 0.75
  random_cropping: true

